### ISSUE TITLE
Focus is  not switching after using Open Expose View

### ISSUE THREAD

**Issue by Blubl** [HPI-SWA-Teaching/SWT17-Project-08#37] opened 2017-06-14 14:29 UTC
After selecting a Window at "Open Expose View" and then selecting another window by normaly clicking on it, it won't get focus so you can't use the buttons of the window anymore.
Like you can see in the screenshot
![grafik](https://user-images.githubusercontent.com/20095713/27137545-86c55a42-511e-11e7-8997-755c0c0230f1.png)

**Comment by jonashering** [comment] 2017-06-14 15:58
Thanks for your comment! Same happened to us, when we reproduced this bug. 

However, we tracked down the reason for this obviously wrong behavior -- we called the wrong methods in order to bring the selected window to front after using the dashboard.

It'll be fixed in the very next release (coming on tuesday)!

**Comment by tomkellog** [comment] 2017-06-15 06:43
* 'sent the wrong message' coughcough

**Closed** 2017-06-15 11:19 UTC
Labels: bug
